name: bro-cpt-boundary-reporting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - geopandas
  - shapely
  - fiona
  - pyproj
  - tqdm
  - pillow
  - openpyxl
  - pip
  - pip:
      - ruptures
